version: "3.4"
services:
    poste:
      image: analogic/poste.io
      # restart: always
      network_mode: "host"
      expose:
        - 25    # SMTP - mostly processing incoming mails
        - 80    # HTTP - redirect to https (see options) and authentication for Let's encrypt service
        - 443   # HTTPS - access to administration or webmail client
        - 110   # POP3 - standard protocol for accessing mailbox, STARTTLS is required before client auth
        - 143   # IMAP - standard protocol for accessing mailbox, STARTTLS is required before client auth
        - 465   # SMTPS - Legacy SMTPs port
        - 587   # MSA - SMTP port used primarily for email clients after STARTTLS and auth
        - 993   # IMAPS - alternative port for IMAP encrypted since connection
        - 995   # POP3S - encrypted POP3 since connections
        - 4190  # Sieve - remote sieve settings
      volumes:
        - ./mail:/data
      environment:
        - HTTPS=ON
        - DISABLE_CLAMAV=TRUE # To disable all ClamAV, it is useful for low mem usage.
        - DISABLE_RSPAMD=TRUE # To disable all Rspamd, it is useful for low mem usage. 